declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_FOOTBALL_API_BASE_URL: string;
    EXPO_PUBLIC_FOOTBALL_API_KEY: string;
    EXPO_PUBLIC_API_PROXY_URL: string;
    EXPO_PUBLIC_FOOTBALL_DATA_PROVIDER: string;
    EXPO_PUBLIC_AUTH_PROVIDER: string;
    EXPO_PUBLIC_FIREBASE_API_KEY: string;
    EXPO_PUBLIC_DEFAULT_SEASON: string;
    EXPO_PUBLIC_DEFAULT_TIMEZONE: string;
  }
}
