export const LEAGUES = {
  PREMIER_LEAGUE: 39,
  CHAMPIONS_LEAGUE: 2,
  LA_LIGA: 140,
  BUNDESLIGA: 78,
  PSL: 288,
} as const;

export const DEFAULT_HOME_LEAGUES = [
  LEAGUES.PREMIER_LEAGUE,
  LEAGUES.CHAMPIONS_LEAGUE,
  LEAGUES.LA_LIGA,
  LEAGUES.BUNDESLIGA,
  LEAGUES.PSL,
];
